const prisma = require("../../src/config/db.config.ts");

async function seedAceDepartment() {
  try {
    await prisma.aceDepartment.createMany({
      data: [
        { name: "Computer Science & Engineering" },
        { name: "Information Technology" },
        { name: "Artificial Intelligence & Data Science" },
        { name: "Software Engineering" },
        { name: "Cyber Security" },
        { name: "Data Analytics" },
        { name: "Information Systems" },
        { name: "Computer Applications (BCA / MCA)" },
        { name: "Electronics & Communication Engineering" },
        { name: "Electrical & Electronics Engineering" },
        { name: "Mechanical Engineering" },
        { name: "Civil Engineering" },
        { name: "Robotics & Automation" },
        { name: "Mechatronics Engineering" },
        { name: "Aerospace / Aeronautical Engineering" },
        { name: "Chemical Engineering" },
        { name: "Biotechnology / Bioengineering" },
        { name: "Materials Science" },
        { name: "Nanotechnology" },
        { name: "Textile Technology" },
        { name: "Petroleum Engineering" },
        { name: "Mining Engineering" },
        { name: "Agricultural Engineering" },
        { name: "Metallurgical Engineering" },
        { name: "Ceramic Engineering" },
        { name: "Architecture" },
        { name: "Urban Planning" },
        { name: "Physics" },
        { name: "Chemistry" },
        { name: "Mathematics" },
        { name: "Statistics" },
        { name: "Life Sciences" },
        { name: "Environmental Science" },
        { name: "Applied Sciences" },
        { name: "Botany" },
        { name: "Zoology" },
        { name: "Microbiology" },
        { name: "Biochemistry" },
        { name: "Geology / Earth Sciences" },
        { name: "Forensic Science" },
        { name: "Home Science / Family & Community Science" },
        { name: "Management Studies" },
        { name: "Business Administration" },
        { name: "Commerce" },
        { name: "Accounting & Finance" },
        { name: "Economics" },
        { name: "Human Resource Management" },
        { name: "Marketing" },
        { name: "Entrepreneurship & Innovation" },
        { name: "Business Analytics" },
        { name: "Banking & Insurance" },
        { name: "Corporate Secretaryship" },
        { name: "Hotel Management & Catering Technology" },
        { name: "Travel & Tourism Management" },
        { name: "Supply Chain & Operations Management" },
        { name: "Law" },
        { name: "Legal Studies" },
        { name: "Public Administration" },
        { name: "Political Science" },
        { name: "International Relations" },
        { name: "Public Policy" },
        { name: "Intellectual Property Rights (IPR)" },
        { name: "Defence / Strategic Studies" },
        { name: "Medicine" },
        { name: "Dentistry" },
        { name: "Pharmacy" },
        { name: "Nursing" },
        { name: "Physiotherapy" },
        { name: "Public Health" },
        { name: "Allied Health Sciences" },
        { name: "Biomedical Sciences" },
        { name: "Medical Laboratory Technology" },
        { name: "Ayurveda" },
        { name: "Homeopathy" },
        { name: "Siddha" },
        { name: "Unani" },
        { name: "Yoga & Naturopathy" },
        { name: "Humanities & Social Sciences" },
        { name: "English & Languages" },
        { name: "Hindi & Indian Languages" },
        { name: "Sanskrit" },
        { name: "History" },
        { name: "Sociology" },
        { name: "Psychology" },
        { name: "Philosophy" },
        { name: "Anthropology" },
        { name: "Education" },
        { name: "Physical Education" },
        { name: "Library & Information Science" },
        { name: "Journalism & Mass Communication" },
        { name: "Fine Arts" },
        { name: "Performing Arts" },
        { name: "Music" },
        { name: "Dance" },
        { name: "Design" },
        { name: "UI/UX Design" },
        { name: "Fashion Design" },
        { name: "Visual Communication" },
        { name: "Animation & Multimedia" },
        { name: "Film & Media Studies" },
        { name: "Agriculture" },
        { name: "Horticulture" },
        { name: "Food Technology" },
        { name: "Dairy Technology" },
        { name: "Veterinary Science" },
        { name: "Fisheries" },
        { name: "Forestry" },
        { name: "Academic Affairs" },
        { name: "Research & Innovation Cell" },
        { name: "Training & Placement Cell" },
        { name: "Career Development Cell" },
        { name: "Startup / Incubation Cell" },
        { name: "International Relations Office" },
        { name: "Examination Cell" },
        { name: "Alumni Association" },
        { name: "Student Council / Union" },
        { name: "Professional Societies (IEEE / ACM / CSI / ISTE)" },
        { name: "Cultural Committee" },
        { name: "Sports Department" },
        { name: "NSS / NCC / Social Outreach" },
        { name: "Interdisciplinary Studies" },
        { name: "Centre of Excellence" },
        { name: "School of Studies" },
        { name: "Faculty of Studies" },
        { name: "Others" },
      ],
      skipDuplicates: true,
    });

    console.log("Ace department seeded successfully.");
  } catch (error) {
    console.error("Error seeding ace department:", error);
    throw error;
  }
}

module.exports = { seedAceDepartment };
